### ISSUE TITLE
ManagedSerialDevice.h:8:20: fatal error: Regexp.h: No such file or directory

### ISSUE THREAD

**Issue by khvalov** [coddingtonbear/arduino-async-duplex#3]
Can't compile under ESP8266 profile

**Comment by coddingtonbear** [comment]
You're missing a dependency; if you install the Regexp library, you'll be good-to-go.

**Comment by khvalov** [comment]
Thanks for reply. Any idea which particular one to install ? There are plenty of Regexp libs availble in google....

**Comment by coddingtonbear** [comment]
Have a glance at the readme's "Requirements" section -- the right one is linked from there.
