### ISSUE TITLE
Error compiling for Arduino Mega (even with installed requirements)

### ISSUE THREAD

**Issue by JJGR93** [coddingtonbear/arduino-async-duplex#5]
Hi, first of all thank you for the library.

I'm trying to make it work with my Arduino Mega so I can manage properly the AT comm with my SIM7000,
but Arduino IDE throws an error when compiling because of the std::functional.

I have installed StandardCplusplus and Regexp libraries.

Thanks!

**Comment by codeflag** [comment]
Hello, 
there is a compiler error.
just try to add in ManagedSerialDevice.cpp line 211 the return statement:

bool ManagedSerialDevice::executeChain(
    const Command* cmdArray,
    uint16_t count,
    std::function<void(MatchState)> _success,
    std::function<void(Command*)> _failure
) {
    **return** ManagedSerialDevice::executeChain(
        cmdArray,
        count,
        ManagedSerialDevice::Timing::ANY,
        _success,
        _failure
    );
}

**Comment by coddingtonbear** [comment]
@codeflag -- I'm not super sure I follow what your request is, but if you file a pull request, I'd be glad to review it.

**Comment by coddingtonbear** [comment]
I'm going to assume for the moment that this was resolved via #8, but please let me know if that's not true.
