### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ggoldsteinDS** [coddingtonbear/arduino-async-duplex#6]
Without a specific license declared, this project is not open source.  Would you consider setting a proper license for this project?  https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by coddingtonbear** [comment]
Whoops!  If you were to file a PR adding the MIT license here, I'd merge it.

**Comment by coddingtonbear** [comment]
Resolved via #7.
